config/routes.rb
Fmm1::Application.routes.draw do
  root to: "static_pages#index"

  resources :sessions,  only: [:new, :create, :destroy]
  namespace :admin do
    resources :users
    resources :teams do
      resources :members
    end
    resources :skills
    resources :positions
    resources :projects do
      resources :user_position_in_projects
    end
    resource :csvs do
      collection do
        post 'export_csv'
        post 'import_csv'
        post 'export_xml'
        post 'import_xml'
      end
    end
  end

  resources :users, only: [:show, :update]
  match '/help', to: 'static_pages#help', via: 'get'
  match '/about', to: 'static_pages#about' , via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

  match '/signin', to: 'sessions#new' , via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
end

app/models/project.rb
class Project < ActiveRecord::Base
  
  has_many :user_position_in_projects, dependent: :destroy
  has_many :users, through: :user_position_in_projects
  
  accepts_nested_attributes_for :user_position_in_projects,
            reject_if: ->attrs { attrs["member"] == '0'}, 
            allow_destroy: true
  
  validates :name, presence: true
  validates :abbreviation, presence: true
  validates :startdate, presence: true
  validates :enddate, presence: true
  
end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < ApplicationController
  # before_action :signed_in_user, :new, :create, :index, :show, :edit, :update, :destroy
  # before_action :admin_user, :new, :create, :edit, :update, :destroy
  
  def new
    @project = Project.new
    if !params[:team_id].nil?
      @team = Team.find params[:team_id]
      @users = User.team_members(@team.id)
    else
      @users = User.all  
    end
    @users.each do |user|
        @project.user_position_in_projects.build user_id: user.id
    end
  end
  
  def create
    @project = Project.new project_params
    if @project.save
      flash.now[:success] = "Created position"
      redirect_to admin_projects_path
    else
      redirect_to root_path
    end
  end
  
  def index
    @projects = Project.paginate page: params[:page], per_page: 3 
  end
  
  def show
    @project = Project.find params[:id]
    @users = @project.users
  end
  
  def edit
    @project = Project.find params[:id]
  end
  
  def update
    @project = Project.find params[:id]
    if !@project.nil?
      if @project.update_attributes project_params
        flash.now[:success] = "Updated Project"
        redirect_to admin_project_path @project
      else
        render :edit
      end
    else
      render root_path
    end
  end  
  
  def destroy
    @project = Project.find params[:id]
    if !@project.nil?
      if @project.destroy 
        flash.now[:success] = "Updated Position"
        redirect_to admin_projects_path
      else
        render :edit
      end
    else
      render root_path
    end
  end
  
  private
  def project_params
    params.require(:project).permit(:name, :abbreviation, 
                                    :startdate, :enddate, :team_id, 
        user_position_in_projects_attributes: [:member, :user_id, 
                                               :position_id])
  end
  
  def admin_user
    redirect_to root_path unless admin_user? current_user
  end
  
end

app/views/admin/projects/_user.html.erb
  <%= f.fields_for :user_position_in_projects do |builder| %>
  	<tr>
	<div class="span4">
		<td><%= builder.check_box :member %></td>
		<td><%= builder.object.user.id %>
			<%= builder.hidden_field :user_id, value: builder.object.user.id%>
		</td>
    	<td><%= builder.object.user.name %></td>
    	<td><%= builder.object.user.email %></td>
    	<td><%= builder.object.user.birth_date.day %> /
    		<%= builder.object.user.birth_date.month %> /
    		<%= builder.object.user.birth_date.year %>
    	</td>
    	<td><%= builder.object.user.profile %></td>
	</tr>
  <% end %>

app/views/admin/projects/edit.html.erb
<% provide(:title, 'Create Project') %>
<h1>Create Project</h1>

<div class="row">
  <div class="span10 offset2">
	<%= form_for @project, as: :project, url: admin_projects_path do |f| %>
	   <%= render 'shared/error_messages', object: f.object %>

	   <p> Team </p>
	   <%= f.collection_select :team_id, Team.all, :id, :name, 
	   									checked: @project.team_id %>

	   <p> Name </p>
	   <%= f.text_field :name %>

	   <p> Abbreviation </p>
	   <%= f.text_field :abbreviation %>
	      
	   <p> Start Date </p>
	   <%= f.date_select :startdate, order: [:month, :day, :year] %>
	      
	   <p> End Date </p>
	   <%= f.date_select :enddate, order: [:month, :day, :year] %>
	 
	  <p> Project Member </p>
	  <table class="table table-striped">

		  <thead>
		    <tr>
		      <th>Member</th>
		      <th>ID</th>
		      <th>Name</th>
		      <th>Email</th>
		      <th>Birthday</th>
		      <th>Profile</th>
		    </tr>
		  </thead>
		  
		  <tbody>
	      <%= f.fields_for :user_position_in_projects do |builder| %>
	      	<tr>
			<div class="span4">
				<td><%= builder.check_box :member, checked: true %></td>
				<td><%= builder.object.user.id %>
					<%= builder.hidden_field :user_id, value: builder.object.user.id%>
				</td>
		    	<td><%= builder.object.user.name %></td>
		    	<td><%= builder.object.user.email %></td>
		    	<td><%= builder.object.user.birth_date.day %> /
		    		<%= builder.object.user.birth_date.month %> /
		    		<%= builder.object.user.birth_date.year %>
		    	</td>
		    	<td><%= builder.object.user.profile %></td>
			</tr>
	      <% end %>
		  </tbody>
		</table>
	  <%= f.submit "Create Project", class: "btn btn-large btn-primary" %>
	<% end %>
  </div>
</div>

app/views/admin/projects/index.html.erb
<% provide(:title, 'Project list') %>
<h1>Project list</h1>

<%= link_to '+ Add Project', new_admin_project_path, 
							 class: "btn btn-medium btn-primary"%></td>

<table class="table table-striped">

  <thead>
    <tr>
      <th>Project ID</th>
      <th>Project Name</th>
      <th>Project Abbreviation</th>
      <th>Start Date</th>
      <th>End Date</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
    <% @projects.each do |project| %>
    <tr>
      <td><%= project.id %></td>
      <td><%= link_to project.name, admin_project_path(project) %></td>
      <td><%= project.abbreviation %></td>
      <td><%= project.startdate.day %>/ <%= project.startdate.month %>/
			<%= project.startdate.year %></td>
      <td><%= project.enddate.day %>/ <%= project.enddate.month %>/
			<%= project.enddate.year %></td>
      <td><%= link_to "Edit", edit_admin_project_path(project) %></td>
      <td><%= link_to "Delete", admin_project_path(project), method: :delete,
              data: { confirm: "You sure?" }, title: project.name %></td>
    </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate %>

app/views/admin/projects/new.html.erb
<% provide(:title, 'Create Project') %>
<h1>Create Project</h1>

<div class="row">
  <div class="span10 offset2">
	<%= form_for([:admin, @project]) do |f| %>
	   <%= render 'shared/error_messages', object: f.object %>
	   
	   <p> Team </p>
	   <%= f.collection_select :team_id, Team.all, :id, :name, selected: 0 %>
	   
	   <p> Name </p>
	   <%= f.text_field :name %>

	   <p> Abbreviation </p>
	   <%= f.text_field :abbreviation %>
	      
	   <p> Start Date </p>
	   <%= f.date_select :startdate, order: [:month, :day, :year] %>
	      
	   <p> End Date </p>
	   <%= f.date_select :enddate, order: [:month, :day, :year] %>
	   
	   <p> Project Member </p>
	   <table id="team_members" class="table table-striped">
		  <thead>
		    <tr>
		      <th>Member</th>
		      <th>ID</th>
		      <th>Name</th>
		      <th>Email</th>
		      <th>Birthday</th>
		      <th>Profile</th>
		    </tr>
		  </thead>
		  
		  <tbody>
	   		<%= render "user", f: f %>
	   	  </tbody>
		</table>
	   
	  <%= f.submit "Create Project", class: "btn btn-large btn-primary" %>
	<% end %>
  </div>
</div>

<script>
	$(document).ready(function(){
	  	$('#project_team_id').change(function(){
	  		$.ajax({
	  		  data: {
	  		  	team_id: $(this).val()
	  		  },
	  		  type: "GET",
	  		  url: "new",
	  		  dataType: "html",
	  		  success: function(data){
		          $('#team_members').html( $( data ).find( '#team_members' ).html());
		      }
	  		});
	  	});
	});
</script>

app/views/admin/projects/show.html.erb
<% provide(:title, @project.name) %>
<div class="row">
  <aside class="span4">
    <section>
      <h1> Subject: <%= @project.name %> </h1>
      <p> Abbreviation: <%= @project.abbreviation %></p>
      <p> Start Date: <%= @project.startdate.day %>/
      	<%= @project.startdate.month %>/ <%= @project.startdate.year %></p>
      <p> End Date: <%= @project.enddate.day %>/ <%= @project.enddate.month %>/
      	<%= @project.enddate.year %></p>
      <%= link_to "Edit", edit_admin_project_path(@project) %>  
    </section>
  </aside>
  
  <div class="span8">
	<% if @users.any? %>
	    <h3>Members</h3>
	    <table class="table table-striped table-bordered">
	      <thead>
	      <tr>
	      	<th>ID</th>
	      	<th>Name</th>
	      	<th>Email</th>
	      	<th>Birthday</th>
	      	<th>Profile</th>
	      </tr>
	      </thead>
	      <tbody>
	      	<% @users.each do |user| %>
		      	<tr>
					<td><%= user.id %></td>
		    		<td><%= user.name %></td>
		    		<td><%= user.email %></td>
		    		<td><%= user.birth_date.day %> /
		    			<%= user.birth_date.month %> /
		    			<%= user.birth_date.year %>
		    		</td>
		    		<td><%= user.profile %></td>
				</tr>
		  	<% end %>
	      </tbody>
	    </table>
	<% end %>
  </div>
</div>