config/routes.rb
Fmm1::Application.routes.draw do
  root to: "static_pages#index"

  resources :sessions,  only: [:new, :create, :destroy]
  namespace :admin do
    resources :users
    resources :teams do
      resources :members
    end
    resources :skills
    resources :positions
    resources :projects do
      resources :user_position_in_projects
    end
    resource :csvs do
      collection do
        post 'export_csv'
        post 'import_csv'
        post 'export_xml'
        post 'import_xml'
      end
    end
  end

  resources :users, only: [:show, :update]
  match '/help', to: 'static_pages#help', via: 'get'
  match '/about', to: 'static_pages#about' , via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

  match '/signin', to: 'sessions#new' , via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
end

app/controllers/admin/csvs_controller.rb
class Admin::CsvsController < ApplicationController
	def new
  end

  def export_csv
    send_data(params[:table].classify.constantize.all.to_csv, {filename: params[:table]+".csv"})
  end

  def import_csv
    params[:table].classify.constantize.import(params[:file])
    redirect_to new_admin_csvs_path, notice: "table " + params[:table] + " successfully imported."
  end

  def export_xml
    send_data(params[:table].classify.constantize.all.to_xml, {filename: params[:table]+".xml"})
  end

  def import_xml
    params[:table].classify.constantize.import_xml(params[:file])
    redirect_to new_admin_csvs_path, notice: "table " + params[:table] + " successfully imported."
  end

end

app/views/admin/csvs/_export_csv.html.erb
<%= form_tag export_csv_admin_csvs_path do %>
  <%= select_tag :table, options_for_select(ActiveRecord::Base.connection.tables) %>
  
  <%= submit_tag "Download", class: "btn btn-default" %>
<% end %>

app/views/admin/csvs/_export_xml.html.erb
<%= form_tag export_xml_admin_csvs_path do %>
  <%= select_tag :table, options_for_select(ActiveRecord::Base.connection.tables) %>
  
  <%= submit_tag "Download", class: "btn btn-default" %>
<% end %>

app/views/admin/csvs/_import_csv.html.erb
<%= form_tag import_csv_admin_csvs_path, multipart: true do %>
  <h3><%= select_tag :table, options_for_select(ActiveRecord::Base.connection.tables) %></h3>

  <h3><%= file_field_tag :file %></h3>
  <%= submit_tag "Import", class: "btn btn-default" %>
<% end %>

app/views/admin/csvs/_import_xml.html.erb
<%= form_tag import_xml_admin_csvs_path, multipart: true do %>
  <h3><%= select_tag :table, options_for_select(ActiveRecord::Base.connection.tables) %></h3>

  <h3><%= file_field_tag :file %></h3>
  <%= submit_tag "Import", class: "btn btn-default" %>
<% end %>