config/routes.rb
Fmm1::Application.routes.draw do
  root to: "static_pages#index"

  resources :sessions,  only: [:new, :create, :destroy]
  namespace :admin do
    resources :users
    resources :teams do
      resources :members
    end
    resources :skills
    resources :positions
    resources :projects do
      resources :user_position_in_projects
    end
    resource :csvs do
      collection do
        post 'export_csv'
        post 'import_csv'
        post 'export_xml'
        post 'import_xml'
      end
    end
  end

  resources :users, only: [:show, :update]
  match '/help', to: 'static_pages#help', via: 'get'
  match '/about', to: 'static_pages#about' , via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

  match '/signin', to: 'sessions#new' , via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
end

app/models/user.rb
class User < ActiveRecord::Base
  
  has_many :user_position_in_projects
  has_many :projects, through: :user_position_in_projects
  
  belongs_to :team
  
  attr_accessor :validate_password
  before_save { self.email = email.downcase }
  before_create :create_remember_token
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6 }, if: :validate_password
  scope :admins, -> { where(permission: 2)}
  scope :members, -> { where(permission: 1)}
  scope :free_users, -> { where(team_id: nil)}
  scope :team_members, ->(team_id) { where(team_id: team_id)}
  
  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private
  def create_remember_token
    self.remember_token = User.encrypt(User.new_remember_token)
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController

  def index
    @users = User.paginate page: params[:page] , per_page: 5
  end

  def show
    @user = User.find params[:id]
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      flash[:notice] = "User has been created"
      redirect_to admin_users_path
    else
      flash[:alert] = "User has not been created"
      render action: 'new'
    end
  end

  def edit
    @user = User.find params[:id]
  end

  def destroy
    user = User.find params[:id]
    if !user.nil?
      if user.destroy
        flash[:success] = "Success destroyed"
      else
        flash[:notice] = "Destroy Failed"
      end
      redirect_to admin_users_path
    else
      redirect_to root_path
    end
  end

  def update
    @user = User.find params[:id]
    if @user.update_attributes user_params
      flash[:success] = "This profile have been updated..."
      redirect_to admin_users_path
    else
      render action: 'edit'
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :birth_date, :permission,
                                                :password, :password_confirmation, :profile)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in_user, only: [:edit, :update]
  before_action :correct_user, only: [:edit, :update]
  def edit
    @user = User.find params[:id]
  end

  def update
    if @user.update_attributes user_params
      flash[:success] = "This profile have been updated..."
      redirect_to @user
    else
    render action: 'edit'
    end
  end

  def show
    @user = User.find params[:id]
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :birth_date, :password, :password_confirmation, :profile)
  end

  def correct_user
    @user = User.find params[:id]
    redirect_to root_path unless current_user? @user
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user, options = { size: 150 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end

  def user_permission_for user
    case user.permission
      when 2
        "admin"
      when 1
        "member"
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user, options = { size: 150 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/admin/users/_form.html.erb
<div class="row well span10">
  <b>Enter the user's information and submitting your account:</b>
  <%= form_for [:admin, @user] do |f|  %>
      <%= render 'shared/error_messages', object: f.object %>
      <div class="row span4">
        <div class="control-group">
         <%= f.label :name %>
          <%= f.text_field :name, class: "form-control" %>
        </div>
        <div class="control-group">
          <%= f.label :email %>
          <%= f.text_field :email, class: "form-control", type: "email" %>
        </div>
        <div class="control-group">
          <%= f.label :birth_date %>
          <%= f.text_field :birth_date,value:  (f.object.birth_date.strftime('%d/%m/%Y') if f.object.birth_date),
                           size: "50", class: "datepicker form-control"%>
        </div>
        <%= f.submit "New user", class: " controls btn btn btn-success" %>

      </div>
      <div class="row span5">
        <div class="control-group">
          <%= f.label :password %>
          <%= f.password_field :password , class: "form-control"%>
        </div>
        <div class="control-group">
          <%= f.label :password_confirmation, "Confirm Password"%>
          <%= f.password_field :password_confirmation, class: "form-control" %>
        </div>
        <div class="control-group">
          <%= f.label :profile%>
          <%= f.text_area :profile, class: "form-control" %>
        </div>

        <div class="btn-group" data-toggle="buttons-radio" >
          <%= f.radio_button :permission,2, id: "first", style: "display:none;" %>
          <label for="first" class="btn btn-info">Admin</label>
          <%= f.radio_button :permission,1, id: "second", style: "display:none;" %>
          <label for="second" class="btn btn-danger">Member</label>
        </div>
      </div>
  <% end %>
</div>

app/views/admin/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for [:admin, @user] do |f| %>
        <%= render 'shared/error_messages', object: f.object %>

        <%= f.label :name %>
        <%= f.text_field :name %>

        <%= f.label :email %>
        <%= f.text_field :email %>

        <%= f.label :birth_date %>
        <%= f.text_field :birth_date,value: (f.object.birth_date.strftime('%d/%m/%Y') if f.object.birth_date), :size => "20", class: 'datepicker'%>

        <%= f.label :password %>
        <%= f.password_field :password %>

        <%= f.label :password_confirmation, "Confirm Password" %>
        <%= f.password_field :password_confirmation %>
        <%= f.label :profile%>
        <%= f.text_area :profile %>
        <%= f.submit "Save changes", class: "btn btn-danger" %>
    <% end %>
  </div>
</div>

app/views/admin/users/index.html.erb
<% provide(:title, 'All members') %>
<h1>All Members: </h1>
<%= will_paginate %>
<table class="table table-hover table-condensed">
  <thead>
  <tr>
    <th>Course ID</th>
    <th>Course Name</th>
    <th>Course Description</th>
    <th>Authority</th>
    <th>Actions</th>
  </tr>
  </thead>
  <tbody>
  <% @users.each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td><%= link_to user.name, [:admin, user] %></td>
        <td><%= user.profile %></td>
        <td><%= user_permission_for user %></td>
        <td>
          <div class="btn-group">
            <a class="btn btn-mini btn-danger dropdown-toggle" data-toggle="dropdown" href="#">
              Action
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Detail",admin_user_path(user)%></li>
              <li><%= link_to "Edit", edit_admin_user_path(user)%></li>
              <li><%= link_to "Delete", admin_user_path(user), method: :delete,
                              data: { confirm: "You sure to delete this account?" }, title: user.name%>
              </li>
            </ul>
          </div>
        </td>
      </tr>
  <% end %>

  </tbody>
</table>
<%= link_to 'Add new user',new_admin_user_path, class: "btn btn-medium btn-info"%>

app/views/admin/users/new.html.erb
<% provide(:title, 'Add new user') %>
<h1>Add new user</h1>
<%= render 'form'%>

app/views/admin/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row span6 offset3">
  <aside class="span4">
    <section>
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>

  </aside>
</div>
<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
        <%= f.label :name %>
        <%= @user.name %>
        <%= f.label :email %>
        <%= @user.email%>
        <%= f.label :profile%>
        <%= @user.profile%>
    <% end %>
  </div>
</div>