config/routes.rb
Fmm1::Application.routes.draw do
  root to: "static_pages#index"

  resources :sessions,  only: [:new, :create, :destroy]
  namespace :admin do
    resources :users
    resources :teams do
      resources :members
    end
    resources :skills
    resources :positions
    resources :projects do
      resources :user_position_in_projects
    end
    resource :csvs do
      collection do
        post 'export_csv'
        post 'import_csv'
        post 'export_xml'
        post 'import_xml'
      end
    end
  end

  resources :users, only: [:show, :update]
  match '/help', to: 'static_pages#help', via: 'get'
  match '/about', to: 'static_pages#about' , via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

  match '/signin', to: 'sessions#new' , via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "MMS", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home",  root_path %></li>
          <li><%= link_to "Help",  help_path %></li>
          <li><%= link_to "About", about_path%></li>
          <li><%= link_to "Positions", admin_positions_path%></li>
          <li><%= link_to "Projects", admin_projects_path%></li>
          <li><%= link_to "Import/Export", new_admin_csvs_path %></li>
          <% if signed_in? %>
            <% if admin_user? current_user %>
              <li><%= link_to "Admin", admin_users_path  %></li>
                  <li id="fat-menu" class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                      Account <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                      <li><%= link_to "Profile", current_user %></li>
                      <li><%= link_to "Edit", edit_admin_user_path(current_user)%></li>
                      <li class="divider"></li>
                      <li>
                        <%= link_to "Sign out", signout_path, method: "delete" %>
                      </li>
                    </ul>
                  </li>
             <% end %>
              <% if member_user? current_user %>
                  <li><%= link_to "Member", current_user %></li>
                  <li id="fat-menu" class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                      Account <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                      <li><%= link_to "Profile",current_user %></li>
                      <li><%= link_to "Edit", edit_user_path(current_user)%></li>
                      <li class="divider"></li>
                      <li>
                        <%= link_to "Sign out", signout_path, method: "delete" %>
                      </li>
                    </ul>
                  </li>
              <% end %>
              <% else %>
              <li><%= link_to "Sign in", signin_path %></li>
            <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fmm1</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <%= render "layouts/header" %>
    <div class="container">
    <%= yield %>
    <%= render "layouts/footer" %>
</div>
</body>
</html>